
services:
  postgres:
    image: postgres:15
    env_file: .env
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app-dev:
    build: ./app
    env_file: .env
    depends_on: [postgres, redis]
    ports:
      - "8010:8000"
    environment:
      - ENVIRONMENT=development
    restart: on-failure
    profiles: [dev]

  app-staging:
    build: ./app
    env_file: .env
    depends_on: [postgres, redis]
    ports:
      - "8011:8000"
    environment:
      - ENVIRONMENT=staging
    restart: on-failure
    profiles: [staging]

  app-prod:
    build: ./app
    env_file: .env
    depends_on: [postgres, redis]
    ports:
      - "8012:8000"
    environment:
      - ENVIRONMENT=production
    restart: on-failure
    profiles: [prod]

volumes:
  pgdata:
