[clinic_servers]
localhost ansible_connection=local

[clinic_servers:vars]
ansible_python_interpreter=/usr/bin/python3
app_image=tshepang981/sa-clinic-api
app_port=8010
postgres_user=clinicuser
postgres_password=clinicpass123
postgres_db=clinicdb
database_url=postgresql://clinicuser:clinicpass123@postgres/clinicdb
redis_url=redis://redis:6379
